### ISSUE TITLE
String from Int/Double/Float

### ISSUE THREAD

**Issue by hukjordanjanaq** [Beyova/SafeDecoder#1]
Hi, how could I manage string decode from Int, Double, Date, etc?

**Comment by canius** [comment]
> Hi, how could I manage string decode from Int, Double, Date, etc?

Hi, do not support string from Numbers currently.

**Comment by canius** [comment]
Hi @jordanjanaq, decoding string from primitive type is supported now in the release 1.0.0

**Comment by hukjordanjanaq** [comment]
Thanks!
